server:
  port: 8080

spring:
  application:
    name: customer-service
  datasource:
    username: 'gabrielmttl'
    url: jdbc:postgresql://localhost:5432/customer
    password: 'password'
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show_sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka